name: resonance
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  flutter_hooks:
  hooks_riverpod:
  riverpod_annotation:
  gap:
  logger:
  cupertino_icons: ^1.0.8
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  rename_app: ^1.6.1
  go_router: ^14.8.0
  intl: any
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.11
  shared_preferences:
  drift: ^2.15.0
  sqlite3_flutter_libs: ^0.5.20
  path_provider: ^2.1.2
  path: ^1.9.0


dev_dependencies:
  build_runner:
  flutter_gen_runner: ^5.8.0
  flutter_launcher_icons: ^0.14.1
  import_sorter: ^4.6.0

  riverpod_generator:
  riverpod_lint:
  flutter_test:
    sdk: flutter
  drift_dev: ^2.15.0

  flutter_lints: ^5.0.0

flutter:
  generate: true
  assets:
    - assets/
  uses-material-design: true

flutter_gen:
  integrations:
    flutter_svg: true

flutter_launcher_icons:
  android: true
  ios: true
  web:
    generate: true
  windows:
    generate: true
  macos:
    generate: true
  image_path: "assets/icon.png"
